name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      LUA_VERSION: 5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          push: true
          build-args: |
            LUA_VERSION=${{ env.LUA_VERSION }}
          tags: ${{ github.repository }}:latest
        env:
          SOURCE_DATE_EPOCH: 0
